import { z } from "zod";
import { sectionSchema } from "./schema";

export const data = [
  {
    "id": 1,
    "clientCode": "CLI-001",
    "nom": "Ahmed Ben Ali",
    "typeClient": "Particulier",
    "matriculeFiscal": "-",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 12,
    "totalFactureHT": 5420.50,
    "totalTVA": 866.80,
    "totalTTC": 6287.30,
    "statut": "Actif"
  },
  {
    "id": 2,
    "clientCode": "CLI-002",
    "nom": "SARL TECH INNOVATION",
    "typeClient": "Professionnel",
    "matriculeFiscal": "1234567",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 28,
    "totalFactureHT": 45320.75,
    "totalTVA": 7251.32,
    "totalTTC": 52572.07,
    "statut": "Actif"
  },
  {
    "id": 3,
    "clientCode": "CLI-003",
    "nom": "Fatima Khaled",
    "typeClient": "Particulier",
    "matriculeFiscal": "-",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 5,
    "totalFactureHT": 1850.00,
    "totalTVA": 296.00,
    "totalTTC": 2146.00,
    "statut": "Actif"
  },
  {
    "id": 4,
    "clientCode": "CLI-004",
    "nom": "ENTREPRISE CONSTRUCTION TUNISIA",
    "typeClient": "Professionnel",
    "matriculeFiscal": "2345678",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 45,
    "totalFactureHT": 125680.25,
    "totalTVA": 20108.84,
    "totalTTC": 145789.09,
    "statut": "Actif"
  },
  {
    "id": 5,
    "clientCode": "CLI-005",
    "nom": "Mohamed Sami Bouhlel",
    "typeClient": "Particulier",
    "matriculeFiscal": "-",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 8,
    "totalFactureHT": 3200.00,
    "totalTVA": 512.00,
    "totalTTC": 3712.00,
    "statut": "Actif"
  },
  {
    "id": 6,
    "clientCode": "CLI-006",
    "nom": "COMMERCE DISTRIBUTION LTÉE",
    "typeClient": "Professionnel",
    "matriculeFiscal": "3456789",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 62,
    "totalFactureHT": 89450.30,
    "totalTVA": 14312.05,
    "totalTTC": 103762.35,
    "statut": "Actif"
  },
  {
    "id": 7,
    "clientCode": "CLI-007",
    "nom": "Leila Mansouri",
    "typeClient": "Particulier",
    "matriculeFiscal": "-",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 3,
    "totalFactureHT": 950.00,
    "totalTVA": 152.00,
    "totalTTC": 1102.00,
    "statut": "Actif"
  },
  {
    "id": 8,
    "clientCode": "CLI-008",
    "nom": "GROUPE INDUSTRIAL SOLUTIONS",
    "typeClient": "Professionnel",
    "matriculeFiscal": "4567890",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 78,
    "totalFactureHT": 256900.50,
    "totalTVA": 41104.08,
    "totalTTC": 298004.58,
    "statut": "Actif"
  },
  {
    "id": 9,
    "clientCode": "CLI-009",
    "nom": "Karim Hadj",
    "typeClient": "Particulier",
    "matriculeFiscal": "-",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 6,
    "totalFactureHT": 2100.75,
    "totalTVA": 336.12,
    "totalTTC": 2436.87,
    "statut": "Actif"
  },
  {
    "id": 10,
    "clientCode": "CLI-010",
    "nom": "SERVICES CONSULTING TUNISIA",
    "typeClient": "Professionnel",
    "matriculeFiscal": "5678901",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 34,
    "totalFactureHT": 67800.00,
    "totalTVA": 10848.00,
    "totalTTC": 78648.00,
    "statut": "Actif"
  },
  {
    "id": 11,
    "clientCode": "CLI-011",
    "nom": "Yasmine Trabelsi",
    "typeClient": "Particulier",
    "matriculeFiscal": "-",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 2,
    "totalFactureHT": 500.00,
    "totalTVA": 80.00,
    "totalTTC": 580.00,
    "statut": "Archivé"
  },
  {
    "id": 12,
    "clientCode": "CLI-012",
    "nom": "MANUFACTURE TEXTILE TUNISIA",
    "typeClient": "Professionnel",
    "matriculeFiscal": "6789012",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 89,
    "totalFactureHT": 345600.75,
    "totalTVA": 55296.12,
    "totalTTC": 400896.87,
    "statut": "Actif"
  },
  {
    "id": 13,
    "clientCode": "CLI-013",
    "nom": "Tariq Mezni",
    "typeClient": "Particulier",
    "matriculeFiscal": "-",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 7,
    "totalFactureHT": 2850.50,
    "totalTVA": 456.08,
    "totalTTC": 3306.58,
    "statut": "Actif"
  },
  {
    "id": 14,
    "clientCode": "CLI-014",
    "nom": "HOTEL RESORT INTERNATIONAL",
    "typeClient": "Professionnel",
    "matriculeFiscal": "7890123",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 52,
    "totalFactureHT": 178950.30,
    "totalTVA": 28632.05,
    "totalTTC": 207582.35,
    "statut": "Actif"
  },
  {
    "id": 15,
    "clientCode": "CLI-015",
    "nom": "Nadia El Amri",
    "typeClient": "Particulier",
    "matriculeFiscal": "-",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 4,
    "totalFactureHT": 1320.00,
    "totalTVA": 211.20,
    "totalTTC": 1531.20,
    "statut": "Actif"
  },
  {
    "id": 16,
    "clientCode": "CLI-016",
    "nom": "AGENCE IMPORT EXPORT TUNISIA",
    "typeClient": "Professionnel",
    "matriculeFiscal": "8901234",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 41,
    "totalFactureHT": 156750.80,
    "totalTVA": 25080.13,
    "totalTTC": 181830.93,
    "statut": "Actif"
  },
  {
    "id": 17,
    "clientCode": "CLI-017",
    "nom": "Samira Ben Youssef",
    "typeClient": "Particulier",
    "matriculeFiscal": "-",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 9,
    "totalFactureHT": 3750.25,
    "totalTVA": 600.04,
    "totalTTC": 4350.29,
    "statut": "Actif"
  },
  {
    "id": 18,
    "clientCode": "CLI-018",
    "nom": "CABINET MEDICAL PLUS",
    "typeClient": "Professionnel",
    "matriculeFiscal": "9012345",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 73,
    "totalFactureHT": 234680.50,
    "totalTVA": 37548.88,
    "totalTTC": 272229.38,
    "statut": "Actif"
  },
  {
    "id": 19,
    "clientCode": "CLI-019",
    "nom": "Abdelaziz Romdhane",
    "typeClient": "Particulier",
    "matriculeFiscal": "-",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 1,
    "totalFactureHT": 350.00,
    "totalTVA": 56.00,
    "totalTTC": 406.00,
    "statut": "Archivé"
  },
  {
    "id": 20,
    "clientCode": "CLI-020",
    "nom": "SOCIETE GENERALE TRANSPORT",
    "typeClient": "Professionnel",
    "matriculeFiscal": "0123456",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 95,
    "totalFactureHT": 456320.75,
    "totalTVA": 73011.32,
    "totalTTC": 529332.07,
    "statut": "Actif"
  },
  {
    "id": 21,
    "clientCode": "CLI-021",
    "nom": "Rania Chouki",
    "typeClient": "Particulier",
    "matriculeFiscal": "-",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 11,
    "totalFactureHT": 4200.50,
    "totalTVA": 672.08,
    "totalTTC": 4872.58,
    "statut": "Actif"
  },
  {
    "id": 22,
    "clientCode": "CLI-022",
    "nom": "RESTAURANT CHAIN TUNISIA",
    "typeClient": "Professionnel",
    "matriculeFiscal": "1123456",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 108,
    "totalFactureHT": 678900.25,
    "totalTVA": 108624.04,
    "totalTTC": 787524.29,
    "statut": "Actif"
  },
  {
    "id": 23,
    "clientCode": "CLI-023",
    "nom": "Hamza Saidani",
    "typeClient": "Particulier",
    "matriculeFiscal": "-",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 15,
    "totalFactureHT": 5890.30,
    "totalTVA": 942.45,
    "totalTTC": 6832.75,
    "statut": "Actif"
  },
  {
    "id": 24,
    "clientCode": "CLI-024",
    "nom": "ENERGIE SOLUTIONS TUNISIA",
    "typeClient": "Professionnel",
    "matriculeFiscal": "2123456",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 66,
    "totalFactureHT": 234567.80,
    "totalTVA": 37530.85,
    "totalTTC": 272098.65,
    "statut": "Actif"
  },
  {
    "id": 25,
    "clientCode": "CLI-025",
    "nom": "Souad Kasraoui",
    "typeClient": "Particulier",
    "matriculeFiscal": "-",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 3,
    "totalFactureHT": 780.00,
    "totalTVA": 124.80,
    "totalTTC": 904.80,
    "statut": "Actif"
  },
  {
    "id": 26,
    "clientCode": "CLI-026",
    "nom": "AGENCE MARKETING DIGITAL",
    "typeClient": "Professionnel",
    "matriculeFiscal": "3123456",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 51,
    "totalFactureHT": 145670.50,
    "totalTVA": 23307.28,
    "totalTTC": 168977.78,
    "statut": "Actif"
  },
  {
    "id": 27,
    "clientCode": "CLI-027",
    "nom": "Djamal Brahim",
    "typeClient": "Particulier",
    "matriculeFiscal": "-",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 13,
    "totalFactureHT": 6200.75,
    "totalTVA": 992.12,
    "totalTTC": 7192.87,
    "statut": "Actif"
  },
  {
    "id": 28,
    "clientCode": "CLI-028",
    "nom": "SOCIETE FINANCIERE TUNISIA",
    "typeClient": "Professionnel",
    "matriculeFiscal": "4123456",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 127,
    "totalFactureHT": 789234.60,
    "totalTVA": 126277.54,
    "totalTTC": 915512.14,
    "statut": "Actif"
  },
  {
    "id": 29,
    "clientCode": "CLI-029",
    "nom": "Aïcha Hamdi",
    "typeClient": "Particulier",
    "matriculeFiscal": "-",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 10,
    "totalFactureHT": 4100.00,
    "totalTVA": 656.00,
    "totalTTC": 4756.00,
    "statut": "Actif"
  },
  {
    "id": 30,
    "clientCode": "CLI-030",
    "nom": "ATELIER ARTISANAL TUNISIA",
    "typeClient": "Professionnel",
    "matriculeFiscal": "5123456",
    "pays": "Tunisie",
    "deviseParDefaut": "TND",
    "nombreFactures": 38,
    "totalFactureHT": 98765.40,
    "totalTVA": 15802.46,
    "totalTTC": 114567.86,
    "statut": "Actif"
  }
] satisfies z.infer<typeof sectionSchema>[];  